### ISSUE TITLE
VS Code on OSX complains about missing `Content-Length`

### ISSUE THREAD

**Issue by MikhailArkhipov** [CXuesong/LanguageServer.NET#4]
VS Code on OSX complains about missing `Content-Length`

![image](https://user-images.githubusercontent.com/12820357/32427312-a3d2eb32-c274-11e7-8288-37aba58eb6b6.png)

Haven't see this on Windows, but will double check.

BTW LanguageServer assembly appears to be built against 0.3.1 streams and does not like 0.3.2. No public tokens either.

**Comment by CXuesong** [comment]
Could you please show me the value of `this.buffer` on the occurrence of exception? It may be helpful.

Also, from your snapshot, `data` contains the leading three letter `Con`. Is it `Content-Length` or `Content-Type`?

**Comment by CXuesong** [comment]
As for `JsonRpc.Standard` dependency, you can try to upgrade `LanguageServer.NET` package to [`v0.1.3-int0`](https://www.nuget.org/packages/CXuesong.LanguageServer.VsCode/0.1.3-int0). Hope it solves this part of the problem.

**Comment by MikhailArkhipov** [comment]
Here

![image](https://user-images.githubusercontent.com/12820357/32476275-145723da-c32b-11e7-9aa4-fd85e406c2b4.png)

**Comment by MikhailArkhipov** [comment]
Data

```
[0..99]
0:67
1:111
2:110
3:116
4:101
5:110
6:116
7:45
8:76
9:101
10:110
11:103
12:116
13:104
14:58
15:32
16:50
17:48
18:54
19:13
20:10
21:67
22:111
23:110
24:116
25:101
26:110
27:116
28:45
29:84
30:121
31:112
32:101
33:58
34:32
35:97
36:112
37:112
38:108
39:105
40:99
41:97
42:116
43:105
```

**Comment by MikhailArkhipov** [comment]
I am not sure actually if this is your code issue... The message comes from the logger in ASP.NET Core MVC, I am wondering if that is there debug output problem actually. It is not sent via `window/logMessage`

**Comment by MikhailArkhipov** [comment]
However, this one does come via window/log

![image](https://user-images.githubusercontent.com/12820357/32477595-5806e35a-c334-11e7-80ab-873a19ad0927.png)

**Comment by CXuesong** [comment]
From the `data` array, I can see there is a `Content-Length` header presenting.
```
67	111	110	116	101	110	116	45	76	101	110	103	116	104	58	32	50	48	54	13	10	67	111	110	116	101	110	116	45	84	121	112	101	58	32	97	112	112	108	105	99	97	116	105
C	o	n	t	e	n	t	-	L	e	n	g	t	h	:	 	2	0	6	\r	\n	C	o	n	t	e	n	t	-	T	y	p	e	:	 	a	p	p	l	i	c	a	t	i
```

From [`messageReader.ts`](https://github.com/Microsoft/vscode-languageserver-node/blob/728dcc1e00fe4e9dda4781fe3fac9680646d5ed7/jsonrpc/src/messageReader.ts#L56-L62), the parsing will just exit and return `undefined`, because it shouldn't have met `\r\n\r\n` sequence this early. Perhaps there already are some characters (esp. `\r\n\r\n` sequence) in the buffer? If so, the previous message might have been chopped off unexpectedly…

**Comment by MikhailArkhipov** [comment]
Not sure. Same thing seems to work on Windows though... Which reminds me that on Mac there is no CRLF usually... But then again, I am not expert in JSON RPC so maybe CRLF is always supposed to be there.

**Comment by MikhailArkhipov** [comment]
OK, looks like ASP.NET Core logger fault. Its messages on Mac leak into the stdout (doesn't happen on Windows) and I think that what makes them to appear on VSC side confusing the reader. Need to figure out why.

Thanks for your help.
