### ISSUE TITLE
CompletionContext is currently missing

### ISSUE THREAD

**Issue by lextm** [CXuesong/LanguageServer.NET#6]
https://microsoft.github.io/language-server-protocol/specification#textDocument_completion

The protocol specification now has CompletionParams defined, which provides more information (like `Invoke` and `TriggerCharacter`. I think this library should be updated to extract them out.

**Comment by CXuesong** [comment]
I've added the new classes (including `CompletionContext`) used in LSP 3.0, and released [v0.2.0-int0](https://github.com/CXuesong/LanguageServer.NET/releases/tag/v0.2.0-int0).

However it seems that CompletionContext is still yet to be supported. From my quick test on demo language server, `contextSupport` is missing… I'm using VSCode 1.20.0.

```json
"completion": {
    "dynamicRegistration": true,
    "completionItem": {
        "snippetSupport": true,
        "commitCharactersSupport": true
    }
},
```

**Comment by lextm** [comment]
According to the protocol change log, this is the new addition made on Nov 27, so it would arrive in future VSCode releases. Not sure if VSCode Insider build already supports it now, will give it a try.

**Comment by CXuesong** [comment]
Updated vscode client support to 1.33. I think this issue can be closed now.

And I'm going to release the next version of LSP support 😃
