### ISSUE TITLE
Problem in connection stability?

### ISSUE THREAD

**Issue by hazama-yuinyan** [CXuesong/LanguageServer.NET#7]
Hi! I'm using this project and developing a language extension for VSCode. Apparently it has a problem in connection stability because it doesn't work when I have used it for some time.
After debugging some time I found that the response handler for the client side will get not called but the server log says it successfully sends back a response. After once that happened, the response handler will never get called anymore but the server will receive messages and send back responses.
And strangely both the server and the client don't complain about losing connection.

I suspect that `JsonRpc` that the project depends on causes the problem, but I'm not sure. Could you take some time for addressing the problem?

**Comment by CXuesong** [comment]
Sure. Let's start with a basic try. Does your document contain non-ASCII characters? You may try to force the console input/output encoding to UTF8 with `Console.Input/OutputEncoding = Encoding.UTF8;` upon startup.

Then, is it possible for me to have access to your language server code, so I can reproduce the problem locally?

**Comment by hazama-yuinyan** [comment]
Thank you! As for document, I'm not using non-ASCII characters even though I'm a Japanese. The problem will occur even though the document only contains ".NET", ".NET Core" or ".NET Standard" or something.
As for forcing the console input/output encoding to UTF-8, it doesn't work.

I think the problem will reproduce for this repository, because I'm using the project almost as it is.
The changes I made are upgrading .NET core version to 2.0 and changing the directory that the language extension loads to 'netcoreapp2.0' because with .NET core 2.0, connections will be closed as soon as you activate the extension. 

Steps to reproduce the problem are as follows: Proceed with the instructions that README.md says and then make completion requests few times(twice or three times). And then the problem should arise. Suddenly even though you make a hover request, the UI doesn't respond. It just says "now loading". And so is for completion requests. It doesn't work. 
I'm not sure the operating system matters but I'm using a Mac. And I'm using the latest VSCode.

**Comment by CXuesong** [comment]
Uhm. Cannot reproduce it right now. Perhaps I need to find someone with Mac. During that time, you may also try to switch an OS ^_^

[Here is the screen recording](https://github.com/CXuesong/LanguageServer.NET/files/1974824/-.test.demo.-._private.-.Visual.Studio.Code.-.Insiders.2018_5_4.10_41_47.zip). I tried it on VSCode 1.23.0 on Windows 10.

**Comment by hazama-yuinyan** [comment]
Ah, after typing some words, try to make hover requests on the typed words several times. Then the problem might occur! Usually, the tooltip tells you the current position, but suddenly it just says now loading. Oh, and make sure that the DemoLanguageServer project depends on .NET Core 2.0!

Oh, I forgot to mention an important point! Put some line breaks so the text will look like the following:
```
.[.NET]
.[.NET Framework]
.[.NET Standard]
```

Without line breaks, the problem doesn't reproduce on my Mac.

By the way, I have a Windows 10 machine as well, so I'm going to try to see if it reproduces on Windows 10 tomorrow.

**Comment by CXuesong** [comment]
Ahh, I see. You mean if I hover on the squiggle line of warnings, sometimes the tip will show a “loading…” text below the lint warning, right? I will look into this tomorrow.

Still, the auto-completion should work without any trouble. If so, I think the problem should be with the demo itself, rather than the JsonRpc library.

**Comment by hazama-yuinyan** [comment]
Ahh, that's not exactly what I meant, but it's still close.

You mouse over some text no matter whether lint warnings appear, a tooltip shows up, right? I meant this tooltip, but the essence is the same, I think.

I've found that the problem reproduces on my Windows 10 machine as well.
I think that the key is hover requests. After making hover requests several times, the problem arises. And I think that it's more likely to reproduce if the text contains line breaks.

Oh, really? After the tooltip doesn't respond, the auto-completion also doesn't work for me. The lint works(Checking whether spelling is correct), though.

**Comment by hazama-yuinyan** [comment]
And as I said above, after the problem arises, the response handler in "vs-code-jsonrpc/lib/main.js" won't get called anymore so I suspect that something interrupts the connection.
I hope it will help you out ;-)

**Comment by CXuesong** [comment]
Sorry, I've forgotten what I've exactly written in the DemoLanguageServer. (Time goes by and I just forgot it. Oops.) But now I think I've get the point (hopefully).

Let me describe the problem again.  if you keep hovering on the text (regardless of the linting warnings) fairly fast, especially when the arrow leaves the text as soon as you can see a "loading…" hover tip, you will never see the hover tip the language server intends to show you; just "loading…" and nothing else.

After reading the code of `textDocument/hover` handler, and [there is a 1000ms delay](https://github.com/CXuesong/LanguageServer.NET/blob/f740f09230078c7be8cf20368631f202eec239d3/DemoLanguageServer/Services/TextDocumentService.cs#L21) before the handler can return. So if you leave the text you used to hover on, in less than 1000ms, the language server client will send a `$/cancelRequest` notification. After that, the hover & auto-completion won't work anymore.

What is interesting is that even at this time, language server can still publish diagnostic information successfully. I will keep investigate on this.

**Comment by hazama-yuinyan** [comment]
> Sorry, I've forgotten what I've exactly written in the DemoLanguageServer. (Time goes by and I just forgot it. Oops.) But now I think I've get the point (hopefully).

Don't worry. Humans will forget. And I suppose forgetting is not necessarily a bad thing :) 

> Let me describe the problem again. if you keep hovering on the text (regardless of the linting warnings) fairly fast, especially when the arrow leaves the text as soon as you can see a "loading…" hover tip, you will never see the hover tip the language server intends to show you; just "loading…" and nothing else.
> After reading the code of textDocument/hover handler, and there is a 1000ms delay before the handler can return. So if you leave the text you used to hover on, in less than 1000ms, the language server client will send a $/cancelRequest notification. After that, the hover & auto-completion won't work anymore.

Yes, that's the problem. To add some explanations, after the problem arises, hover doesn't work even if you stay on texts and wait for the tooltip changing. It just makes me waiting forever.

> What is interesting is that even at this time, language server can still publish diagnostic information successfully. I will keep investigate on this.

That's the strange point. Because the source code for the language server is fairy simple, I suspect that `JsonRpc` causes the problem. It's because it seems there is no room for such bugs to come in in the language server!
I hope we will find the cause quickly!

**Comment by CXuesong** [comment]
So the bug is really with `JsonRpc.Streams` package. I've just published [v0.4.2](https://www.nuget.org/packages/CXuesong.JsonRpc.Streams/0.4.2) of `CXuesong.JsonRpc.Streams`. You can upgrade the dependency and try again :-) Though it may take several minutes for the new version to be visible publicly.

I will add some tests regarding to this issue later; after that, I will add a new release on `CXuesong/JsonRpc.Standard` repos, too. Before then, should you discover any further issue, please tell me without hesitation!

**Comment by hazama-yuinyan** [comment]
Hooray! The problem now is gone!
Good job! And thank you!
Now my language extension also might work!

**Comment by CXuesong** [comment]
Glad that you told me about this issue. Actually this is a major one. All the language server with cancellation support would be affected by this bug!
