### ISSUE TITLE
Help with my language extension...?

### ISSUE THREAD

**Issue by hazama-yuinyan** [CXuesong/LanguageServer.NET#9]
Hi, yet another time! This time, the symptom is similar to the first one, that is, the response handler will not get called. But this time from the beginning. After the initialized event is called the `handleResponse` function in node_modules/vscode-jsonrpc/main.js won't never get called. So the hover events will never happen and so will the completion events do(I commented out lint events so it's natural it's not happening). The server log says that it successfully returns the responses, though.
I have completely no idea of how that happens because it worked until I have modified it. It worked until I made modifications to the ExpressoLanguageServer(DemoLanguageServer) project, so something related to it prevents it from working but I have completely no idea.

You can download the source codes that reproduce the problem [here][expresso]. Before you begin debugging, you should do the following:

1. Go to Expresso/EditorSupport/colorizer/ and copy the contents to your ~/.vscode/extensions.
2. This installs the basic language extension for Expresso, so you can now use the language id "expresso".
3. Run `git submodule update --init` to initialize the submodules that the projects depend on.

And then you need to do the following to compile:

1. Open Libraries/NRefactory/ICSharpCode.NRefactory/TypeSystem/Implementation/AbstractUnresolvedEntity.cs and add the `protected` modifier to the lines 44 and 55(original contents: `internal BitVector16 flags;` and `internal const ushort FlagHasExtensionMethods = 0x0080;` repectively)
2. Open Libraries/NRefactory/ICSharpCode.NRefactory/TypeSystem/Implementation/UnresolvedSecurityDeclarationBlob.cs and comment out the lines 30 and from 47 to 55 with a block comment(effectively comment out the declaration of `static readonly ITypeReference permissionSetAttributeTypeReference = typeof(System.Security.Permissions.PermissionSetAttribute).ToTypeReference();` and its use)

Then you can open Expresso/EditorSupport/language-server/LanguageServer.NET.sln in Visual Studio and Expresso/EditorSupport/language-server/Client/VsCode/ in VsCode as your README.md says, build the solution and test-run the language server in VsCode. As you would see, it's not working for the very first time you would hover over some texts or type some texts.

I doubt that there is some bug again in `JsonRpc`, but I'm not sure because my ExpressoLanguageServer project is fairy simple.

So could you help me out again, please?

[expresso]: https://github.com/hazama-yuinyan/Expresso

**Comment by CXuesong** [comment]
Sure. Since I didn't have much time to spare today (pain of graduation 🌚), I will check it out tomorrow.

**Comment by hazama-yuinyan** [comment]
Thank you so much! It will really help!

**Comment by CXuesong** [comment]
By running your LSP directly, I can see there is output directly emitted into console output, and I think that screwed the RPC channel up.

To reproduce the issue, I changed [`PartwiseStreamMessageReader`/`Writer`](https://github.com/hazama-yuinyan/Expresso/blob/c72723ea4d8f6c9a8250985afca95649cf5fccde/EditorSupport/language-server/DemoLanguageServer/Program.cs#L42) to `ByLineTextMessageReader`/`Writer`, so the LSP will accept and writes JSON in single lines without `Content-Length` and stuff.

Then I replayed the JSON requests by copying the message from log. Especially, I copied the client request (fron VsCode-side) as shown in the following part of the log
```json
> {"id":0,"method":"initialize","params":{"processId":19868,"rootPath":"ed:\\test","rootUri":"file:///d%3A/test","capabilities":{"workspace":{"applyEdit":true,"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true}},"textDocument":{"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true}},"hover":{"dynamicRegistration":true},"signatureHelp":{"dynamicRegistration":true},"definition":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true},"codeAction":{"dynamicRegistration":true},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true}}},"trace":"off"},"jsonrpc":"2.0"}
< {"id":0,"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"willSave":true,"willSaveWaitUntil":false,"save":null},"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":"."},"signatureHelpProvider":{"triggerCharacters":"()"},"definitionProvider":false,"referencesProvider":false,"documentHighlightProvider":false,"documentSymbolProvider":false,"workspaceSymbolProvider":false,"codeActionProvider":false,"codeLensProvider":null,"documentFormattingProvider":false,"documentRangeFormattingProvider":false,"documentOnTypeFormattingProvider":null,"renameProvider":false,"documentLinkProvider":null,"executeCommandProvider":null,"experimental":null}},"jsonrpc":"2.0"}
> {"method":"initialized","params":{},"jsonrpc":"2.0"}
<C{"method":"window/showMessage","params":{"type":3,"message":"Hello from language server."},"jsonrpc":"2.0"}
< 
> {"method":"workspace/didChangeConfiguration","params":{"settings":{"expressoLanguageServer":{}}},"jsonrpc":"2.0"}
< 
> {"method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///d%3A/test/fib.exs","languageId":"expresso","version":1,"text":"module main;\r\n\r\n\r\ndef main()\r\n{\r\n    let n = 10000;\r\n\tvar a = 0, b = 1;\r\n\twhile b < n {\r\n\t\tprint(b);\r\n\t\ta, b = b, a + b;\r\n\t}\r\n}"}},"jsonrpc":"2.0"}
< 
```
The console input & output is as follows
![image](https://user-images.githubusercontent.com/11611687/39930928-92063494-556e-11e8-8416-fe36bd6ddeb4.png)
Obviously, it seems the parser log got emitted to the console, and the client is much likely to get confused.

**Comment by CXuesong** [comment]
Btw, I've added some files to `Expresso.NETCore.csproj` to make the compilation work.
```diff
diff --git a/EditorSupport/language-server/Expresso.NETCore/Expresso.NETCore.csproj b/EditorSupport/language-server/Expresso.NETCore/Expresso.NETCore.csproj
index 330a8ef..92fbdec 100644
--- a/EditorSupport/language-server/Expresso.NETCore/Expresso.NETCore.csproj
+++ b/EditorSupport/language-server/Expresso.NETCore/Expresso.NETCore.csproj
@@ -1,4 +1,4 @@
-<Project Sdk="Microsoft.NET.Sdk">
+<EF><BB><BF><Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
     <TargetFramework>netcoreapp2.0</TargetFramework>
@@ -201,6 +201,12 @@
     <Compile Include="..\..\..\Expresso\Ast\GeneralScope\AliasDeclaration.cs">
       <Link>Ast\GeneralScope\AliasDeclaration.cs</Link>
     </Compile>
+    <Compile Include="..\..\..\Expresso\Ast\GeneralScope\AttributeNode.cs">
+      <Link>Ast\GeneralScope\AttributeNode.cs</Link>
+    </Compile>
+    <Compile Include="..\..\..\Expresso\Ast\GeneralScope\AttributeSection.cs">
+      <Link>Ast\GeneralScope\AttributeSection.cs</Link>
+    </Compile>
     <Compile Include="..\..\..\Expresso\Ast\GeneralScope\CommentNode.cs">
       <Link>Ast\GeneralScope\CommentNode.cs</Link>
     </Compile>
```

**Comment by hazama-yuinyan** [comment]
So it doesn't work because the parser prints its output to the std.out?
I completely forgot about it! Thank you so much, and I'm sorry for taking your time to do such a silly task. Then I'll rewrite it so that it doesn't print outputs to std.out and report it here! ;(
Thank you so much again!

**Comment by CXuesong** [comment]
You're welcome. Actually, this issue is a common case… See #4 😂

Perhaps I should put such debugging trick into FAQ…

**Comment by hazama-yuinyan** [comment]
At least you should write about the program using std.in/out for IPC, I guess. People usually don't notice about it ;-)

**Comment by CXuesong** [comment]
Wierd. I cannot quite remember how I've learned that VsCode uses stdio for JSON RPC; yet I have just realized the official LSP specification actually said nothing about transportation…

Thank you for reminding me of this!

**Comment by hazama-yuinyan** [comment]
Umm... as a common sense? You would use std.in/out for IPC in general so you assumed it for LSP as well without realizing it.

Bingo! You're right! It's because the parser prints its output to the std.out. Adding #if directives to Console.WriteLine statements to ignore them when the parser runs as a part of a language server has made it work.

Thank you so much again! You're my hero ; - )
